export const norwegian = {
  inStock: "På lager",
  outOfStock: "Utsolgt",
  removeProduct: "Fjern produkt",
  addToCart: "Legg i handlekurv",
  adjustQuantity: "Juster antall",
  yourCartHas: "Din handlekurv har",
  items: "vare(r)",
  viewProduct: "Se produkt",
  yourCartSummary: "Din handlekurv sammendrag",
  signInToCheckout: "Logg inn til kassen",
  deliveryAddress: "Leveringsadresse",
  successPayment: "Takk, betalingen din var vellykket",
  bestsellers: "Best Selgere",
  newArrivals: "Nyankomne",
  signIn: "Logg inn",
  singOut: "Logg ut",
  shop: "Butikk",
  cart: "Kurven",
  dashboard: "Dashbord",
  home: "Hjem",
  signup: "Melde deg på",
  relatedProducts: "Relaterte produkter",
  search: "Søke",
  filterByCategories: "Filtrer etter kategorier",
  filterByPrice: "Filtrer etter prisklasse",
  products: "Produkter"
};
